import type { PlaylistState } from "./types";

export function createDemoPlaylistState(): PlaylistState {
  return {
    tracks: [
      { id: "track-1", label: "Drums", color: "#e85d75" },
      { id: "track-2", label: "Bass", color: "#46b871" },
      { id: "track-3", label: "Chords", color: "#d9a441" },
      { id: "track-4", label: "Lead", color: "#39a8c9" },
      { id: "track-5", label: "Vox", color: "#c970d8" },
      { id: "track-6", label: "Automation", color: "#b7d957" },
      { id: "track-7", label: "Perc FX", color: "#f0703f" },
      { id: "track-8", label: "Transitions", color: "#8fd3a8" },
    ],
    clips: [
      {
        id: "clip-drums-1",
        type: "pattern",
        trackId: "track-1",
        start: 0,
        duration: 16,
        label: "Main drums",
        color: "#d94f68",
      },
      {
        id: "clip-drums-2",
        type: "pattern",
        trackId: "track-1",
        start: 18,
        duration: 10,
        label: "Break hats",
        color: "#f07f55",
      },
      {
        id: "clip-bass-1",
        type: "audio",
        trackId: "track-2",
        start: 4,
        duration: 18,
        label: "Bass take",
        color: "#30a96b",
      },
      {
        id: "clip-chords-1",
        type: "pattern",
        trackId: "track-3",
        start: 8,
        duration: 16,
        label: "Chord stack",
        color: "#c99731",
      },
      {
        id: "clip-lead-1",
        type: "pattern",
        trackId: "track-4",
        start: 24,
        duration: 14,
        label: "Lead answer",
        color: "#2ea0bd",
      },
      {
        id: "clip-vocal-1",
        type: "audio",
        trackId: "track-5",
        start: 12,
        duration: 22,
        label: "Vocal chop",
        color: "#b862d0",
      },
      {
        id: "clip-auto-1",
        type: "automation",
        trackId: "track-6",
        start: 4,
        duration: 32,
        label: "Filter cutoff",
        color: "#a9cc45",
        points: [
          { id: "auto-1-pt-1", time: 0, value: 0.22 },
          { id: "auto-1-pt-2", time: 6, value: 0.72 },
          { id: "auto-1-pt-3", time: 13, value: 0.48 },
          { id: "auto-1-pt-4", time: 21, value: 0.88 },
          { id: "auto-1-pt-5", time: 32, value: 0.34 },
        ],
      },
      {
        id: "clip-fx-1",
        type: "audio",
        trackId: "track-8",
        start: 30,
        duration: 8,
        label: "Impact",
        color: "#ef7146",
      },
    ],
    viewport: {
      scrollX: 0,
      scrollY: 0,
      pxPerBeat: 28,
      width: 1,
      height: 1,
    },
    snap: {
      mode: "beat",
      lastActiveMode: "beat",
    },
    selection: {
      clipIds: [],
      automationPointIds: [],
    },
    marquee: null,
    contextMenu: null,
    hover: null,
    playPosition: {
      time: 0,
      isRunning: false,
    },
    tool: "select",
    clipboard: null,
    stretchMode: false,
    markers: [
      { id: "m-start", time: 0, kind: "start", label: "Start" },
      { id: "m-loop-a", time: 16, kind: "loop", label: "Loop A" },
      { id: "m-loop-b", time: 40, kind: "loop", label: "Loop B" },
    ],
    transport: { mode: "song", recording: false },
    dragPreview: null,
    snapHint: null,
    tooltip: null,
  };
}
