export const DEFAULT_PLAYLIST_METRICS = {
    rulerHeight: 38,
    trackHeaderWidth: 148,
    trackHeight: 72,
    clipPaddingY: 7,
    clipTitleHeight: 20,
    resizeHandleWidth: 8,
    automationPointRadius: 6,
    minClipDuration: 0.25,
    minPxPerBeat: 8,
    maxPxPerBeat: 96,
    beatsPerBar: 4,
    trackOverscan: 3,
    timelineOverscanPx: 120,
    playMarkerHitWidth: 14,
    scrollbarSize: 14,
    scrollbarThumbMin: 44,
    scrollbarVirtualRangePx: 120000,
    contextMenuWidth: 228,
    contextMenuItemHeight: 28,
};
